version: '3'
services:
  ubuntu1:
    container_name: ubuntu1
    hostname: ubuntu1
    image: "ubuntu:custom"
    ports:
     - "2222:22"
    links:
     - ubuntu2:ubuntu2
    working_dir: /
    tty: true
  ubuntu2:
    image: "ubuntu:custom"
    container_name: ubuntu2
    hostname: ubuntu2
    ports: 
     - "2223:22"
    working_dir: /
    tty: true
  
