FROM ubuntu:16.04
COPY ./sources.list /etc/apt/
COPY ./start.sh Dockerfile-ubuntu /root/conf/
RUN apt-get update \
	&& apt-get install -y curl \
    && apt-get install -y dnsutils \
    && apt-get install -y iputils-ping \
    && apt-get install -y man-db    \
    && apt-get install -y net-tools \
    && apt-get install -y openssh-server \
    && apt-get install -y traceroute    \
    && apt-get install -y vim \
    && rm -rf /var/lib/apt/lists/*  \
    && echo "root:123" | chpasswd  \
    && sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config 
EXPOSE 80 22 23
ENTRYPOINT ["/root/conf/start.sh"]


